# Generated by Django 3.1.2 on 2020-10-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
