# Generated by Django 3.1.2 on 2020-10-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201012_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
    ]
